
export const GET_SLIDER = 'redux/GET_SLIDER';
export const GET_SLIDER_REQUEST = 'redux/GET_SLIDER_REQUEST';
export const GET_SLIDER_REQUEST_SUCCESS = 'redux/GET_SLIDER_REQUEST_SUCCESS';
export const GET_SLIDER_REQUEST_FAILURE = 'redux/GET_SLIDER_REQUEST_FAILURE';
export const GET_SLIDER_REQUEST_END = 'redux/GET_SLIDER_REQUEST_END';
